### ISSUE TITLE
Crash if running Wayland

### ISSUE THREAD

**Issue by C0rn3j** [gantsign/ansible-role-visual-studio-code-extensions#117]
This role works great on X11, but on a system running Wayland the playbook fails.

System:
```yaml
Operating System: Arch Linux
KDE Plasma Version: 5.25.5
KDE Frameworks Version: 5.98.0
Qt Version: 5.15.6
Kernel Version: 5.19.10-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 3600 6-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: AX370-Gaming K5
```
Playbook:
```yaml
- name: Install Visual Studio Code extensions
  when: user_accts.stdout.find('answerDE="yes"') != -1
  ansible.builtin.include_role:
    name: gantsign.visual-studio-code-extensions
  vars:
    visual_studio_code_extensions_build: oss
    users:
    - username: '{{ username }}'
      visual_studio_code_extensions:
        - vsciot-vscode.vscode-arduino # Arduino
        - ms-vscode.cpptools           # C/C++
        - hediet.vscode-drawio         # Draw.io Integration
        - eamodio.gitlens              # GitLens
        - oderwat.indent-rainbow       # ident-rainbow
        - timonwong.shellcheck         # shellcheck
        - redhat.ansible               # Ansible support
      visual_studio_code_extensions_absent:
        - zbr.vscode-ansible           # Deprecated and moved to redhat.ansible
```

Error:
```yaml
failed: [luxuria] (item=c0rn3j: redhat.ansible) => changed=false 
  ansible_loop_var: item
  item:
  - username: c0rn3j
    visual_studio_code_extensions_absent:
    - zbr.vscode-ansible
  - redhat.ansible
  msg: |-
    Error querying installed extensions [redhat.ansible]: [345563:0925/023604.256892:ERROR:ozone_platform_x11.cc(247)] Missing X server or $DISPLAY
    [345563:0925/023604.256928:ERROR:env.cc(226)] The platform failed to initialize.  Exiting.
    The futex facility returned an unexpected error code.
```

This issue can be reproduced without ansible in the mix, simply SSHing into the machine and running extensions list.

It fails unless XDG_SESSION_TYPE is set to wayland.

```console
(ssh) c0rn3j@Luxuria : ~
[0] % /usr/bin/code --list-extensions redhat.ansible
[350012:0925/024246.929835:ERROR:ozone_platform_x11.cc(247)] Missing X server or $DISPLAY
[350012:0925/024246.929874:ERROR:env.cc(226)] The platform failed to initialize.  Exiting.
The futex facility returned an unexpected error code.
[1]    350012 IOT instruction (core dumped)  /usr/bin/code --list-extensions redhat.ansible

(ssh) c0rn3j@Luxuria : ~
[134] % echo $XDG_SESSION_TYPE       
tty

(ssh) c0rn3j@Luxuria : ~
[0] % XDG_SESSION_TYPE=wayland /usr/bin/code --list-extensions redhat.ansible
[350680:0925/024312.269996:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is egl, ANGLE is 
Warning: 'ozone-platform-hint' is not in the list of known options, but still passed to Electron/Chromium.
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to open nvidia-drm: /usr/lib/dri/nvidia-drm_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib/dri, suffix _dri)
failed to load driver: nvidia-drm
MESA-LOADER: failed to open zink: /usr/lib/dri/zink_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib/dri, suffix _dri)
failed to load driver: zink
MESA-LOADER: failed to open kms_swrast: /usr/lib/dri/kms_swrast_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib/dri, suffix _dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib/dri, suffix _dri)
failed to load swrast driver
denoland.vscode-deno
eamodio.gitlens
golang.go
hediet.vscode-drawio
marlinfirmware.auto-build
ms-python.python
ms-python.vscode-pylance
ms-vscode.cpptools
oderwat.indent-rainbow
platformio.platformio-ide
redhat.ansible
redhat.vscode-yaml
timonwong.shellcheck
vsciot-vscode.vscode-arduino
```
