### ISSUE TITLE
Provide ability to delete / remove extension

### ISSUE THREAD

**Issue by NileshGule** [gantsign/ansible-role-visual-studio-code-extensions#14]
Provide ability to remove / delete an installed extension

**Comment by freemanjp** [comment]
I don't have a need for this as I just rebuild my VM whenever there are changes to my development environment, but I'd be happy to accept a pull request for something like:

```yaml
- role: gantsign.visual-studio-code-extensions
  users:
    - username: vagrant
      visual_studio_code_extensions:
        - streetsidesoftware.code-spell-checker
        - wholroyd.jinja
      visual_studio_code_extensions_absent:
        - donjayamanne.python
```

The keyword `absent` is the convention for ensuring features are removed in Ansible.
